EcommerceApp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'))
]

urlpatterns +=  static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views

urlpatterns = [
    path('',views.home,name='home'),
    path('about',views.about,name='about'),
    path('product-register',views.product_register,name='product_register'),
    path("dashboard/<str:pk>", views.dashboard, name="dashboard"),
    path("update/<str:pk>", views.updateItem, name="update"),
    path("delete/<str:pk>", views.deleteItem, name="delete"),
    path("delete-order/<str:pk>", views.deleteOrder, name="deleteOrder"),
    path('login',views.login_user,name='login'),
    path('settings',views.acc_settings,name='settings'),
    path('logout',views.logout_user,name='logout'),
    path('sign-up',views.Signup,name='sign-up'),
    path('info/<str:pk>',views.Cart_order,name='info'),
    path('status/<str:pk>',views.status_update,name='status_update'),
    path('reset_password',auth_views.PasswordResetView.as_view(template_name="main/resetpass.html"),name='reset_password'),
    path('reset_password_done',auth_views.PasswordResetDoneView.as_view(template_name="main/resetdone.html"),name='password_reset_done'),
    path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name="main/reset.html"),name='password_reset_confirm'),
    path('reset_password_complete',auth_views.PasswordResetCompleteView.as_view(template_name="main/resetcomplete.html"),name='password_reset_complete'),
    path('payment',views.payment,name='payment'),
    path('order-summary',views.summary,name='order-summary'),
    path('cart-update/<str:pk>/<str:action>/',views.update_cart,name='update-cart'),
    path('cart-delete-item/<str:pk>',views.delete_cart_item,name='cart-delete-item'),
    path('checkout',views.checkout,name='checkout'),
    # path('add-coupon',views.addCoupon,name='add-coupon'),

]

main/models.py
from email.policy import default
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import User
from django import forms
from django_countries.fields import CountryField

# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,null=True)
    first_name = models.CharField(max_length=100,null=True)
    last_name = models.CharField(max_length=100,null=True)
    phone= models.CharField(max_length=100,null=True)
    profile_picure = models.ImageField(null=True,blank=True,error_messages = {'invalid':("Image files only")})
    creator = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user)

class Products(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    product_name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.CharField(max_length=10000,null=False,default='0')
    tags = models.CharField(max_length=100,null=True)
    Image = models.ImageField(null=True,blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.product_name

class Orders(models.Model):
    STATUS = (
        ('Pending','Pending'),
        ('Out For Delivary','Out For Delivary'),
        ('Delivered','Delivered')
    )
    seller =  models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    item = models.ForeignKey(Products,on_delete=models.CASCADE,null=True)
    qty = models.CharField(max_length=190)
    status = models.CharField(max_length=190,choices=STATUS,default='Pending')
    date_ordered = models.DateTimeField(auto_now_add=True)
    
   


class OrderItems(models.Model):
    user =  models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    item = models.ForeignKey(Products,on_delete=models.CASCADE,null=True)
    qty = models.IntegerField()
    ordered = models.BooleanField(default=False)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.item)

    def price(self):
        return int(self.qty) * int(self.item.price)
    
    def get_total(self):
        x = 0
        for i in self.item.all():
            x+= int(i.price())
        if self.coupon:
            x -= self.coupon.amount
        return x

class Address(models.Model):
    
    ADDRESS_CHOICES = (
        ('B', 'Billing'),
        ('S', 'Shipping'),
    )
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'

class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code

main/forms.py
from dataclasses import fields
from importlib import import_module
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django import forms
from .models import *
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget
from django.db import models

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class Profile(ModelForm):
    profile_picure = forms.ImageField(label=('Update Profile'),required=False, \
                                    error_messages ={'invalid':("Image files only")},\
                                    widget=forms.FileInput)
    class Meta:
        model = Customer
        fields = '__all__'
        exclude= ['user']

class Product(ModelForm):
    class Meta:
        model = Products
        fields = '__all__'
        exclude= ['user']

class order(ModelForm):
    class Meta:
        model = Orders
        fields = '__all__'
        exclude = ['item','seller','status']

class Updateorder(ModelForm):
    class Meta:
        model = Orders
        fields = '__all__'
        exclude = ['item','seller','qty']


PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'PayPal')
)


class CheckoutForm(forms.Form):
    shipping_address = forms.CharField(required=False)
    shipping_address2 = forms.CharField(required=False)
    shipping_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    shipping_zip = forms.CharField(required=False)

    billing_address = forms.CharField(required=False)
    billing_address2 = forms.CharField(required=False)
    billing_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    billing_zip = forms.CharField(required=False)

    same_billing_address = forms.BooleanField(required=False)
    set_default_shipping = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)
    set_default_billing = forms.BooleanField(required=False)
    use_default_billing = forms.BooleanField(required=False)

    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PAYMENT_CHOICES)


class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Promo code',
        'aria-label': 'Recipient\'s username',
        'aria-describedby': 'basic-addon2'
    }))


class RefundForm(forms.Form):
    ref_code = forms.CharField()
    message = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 4
    }))
    email = forms.EmailField()


class PaymentForm(forms.Form):
    stripeToken = forms.CharField(required=False)
    save = forms.BooleanField(required=False)
    use_default = forms.BooleanField(required=False)

main/views.py
from math import prod
from django.shortcuts import render,redirect,get_object_or_404
from.forms import *
from django.contrib.auth import authenticate,login,logout
from .filters import SearchFilter
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import *
from django.core.paginator import Paginator,EmptyPage
from django.contrib import messages

# Create your views here.

def home(request):
    if 'q' in request.GET:
        q= request.GET['q']
        product =  Products.objects.filter(Q(product_name__contains=q) |
                              Q(product_name__contains=q) |
                              Q(product_name__istartswith =q) |
                              Q(product_name__istartswith = q) |
                              Q(product_name__iendswith = q)|
                              Q(tags__istartswith = q) |
                              Q(tags__contains = q) |
                              Q(tags__iendswith = q) )
    else:
        product = Products.objects.all()
    paginator = Paginator(product,8)
    page_num = request.GET.get('page',1)
    num = paginator.num_pages
    try:
        page = paginator.page((page_num))
    except EmptyPage:
        page = paginator.page(1)

    item =  Products.objects.all()

    cart_items = OrderItems.objects.count()

    context = {'products':page,'num':num,'items':item,'count':cart_items}
    return render(request,'main/index.html',context)

def login_user(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request,username=username,password=password)
        print(request.POST)

        if user is not None:
            login(request,user)
            return redirect('home')

    context= {}
    return render(request,'main/login.html',context)

def dashboard(request,pk):
    customer = Customer.objects.get(id=pk)
    order = request.user.orders_set.all()
    pending = order.filter(status='Pending').count()
    delivered = order.filter(status='Delivered').count()
    items = Products.objects.get_queryset()
    context= {'items':items,'orders':order,'pending':pending,'delivered':delivered}
    return render(request,'main/dashboard_customer.html',context)

def acc_settings(request):
    customer = request.user.customer
    form = Profile(instance=customer)
    print(request.FILES)
    if request.method == "POST":
        form = Profile(request.POST,request.FILES,instance=customer)
        if form.is_valid():
            form.save()
            return redirect('settings')
    context= {'form':form}
    return render(request,'main/account_settings.html',context)

def logout_user(request):
    logout(request)
    return redirect('home')

def Signup(request):
    form   = UserForm()
    if request.method == "POST":
        print(request.POST)
        form = UserForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect('login')
    context= {'form':form}
    return render(request,'main/sign-up.html',context)

def Cart_order(request,pk):
    product = Products.objects.get(id=pk)
    seller = product.user
    if request.method == "POST":
        form = order(request.POST)
        print(request.POST)
        print(form.is_valid())
        if form.is_valid():
            x = form.save(commit=False)
            x.item = product
            x.seller = seller
            x.save()
    cart_items = OrderItems.objects.count()
    context= {'product':product,'count':cart_items}
    return render(request,'main/info.html',context)

def product_register(request):
    customer = User.objects.get(username=request.user)
    form = Product(instance=customer)
    if request.method == "POST":
        form = Product(request.POST,request.FILES)
        print(form.is_valid())
        if form.is_valid():
            x = form.save(commit=False)
            x.user = request.user
            x.save()

            return redirect(f'dashboard/{request.user.customer.id}')
    context= {'form':form}
    return render(request,'main/products_register.html',context)


def updateItem(request,pk):
    productitem = Products.objects.get(id=pk)
    form = Product(instance=productitem)
    context = {'form':form}
    form = Product(request.POST,request.FILES,instance=productitem)
    if form.is_valid():
        form.save()
        return redirect(f'/dashboard/{request.user.customer.id}')
    return render(request,'main/products_register.html',context)

def deleteItem(request,pk):
    productitem = Products.objects.get(id=pk)
    if request.method == 'POST':
        productitem.delete()
        return redirect(f'/dashboard/{request.user.customer.id}')
    context = {'product':productitem}
    return render(request,'main/delete_product.html',context)

def about(request):
    context = {}
    return render(request,'main/about.html',context)

def status_update(request,pk):
    orderitem = Orders.objects.get(id=pk)
    status = request.POST
    print(status)
    form = Updateorder(request.POST,instance=orderitem)
    print(form.is_valid())
    if form.is_valid():
        form.save()
        return redirect(f'/dashboard/{request.user.customer.id}')
    context = {}
    return render(request,'main/status_upadate.html',context)

def deleteOrder(request,pk):
    order =  Orders.objects.get(id=pk)
    if request.method == 'POST':
        order.delete()
        return redirect(f'/dashboard/{request.user.customer.id}')
    context = {'product':order}
    return render(request,'main/delete_order.html',context)


def payment(request):
    context= {}
    return render(request,'main/payment.html',context)

def summary(request):
    orders = request.user.orderitems_set.all()
    final_price = 0
    for i in orders:
        final_price += i.price()
    print(final_price)
    context= {'orders':orders,'finalprice':final_price}
    return render(request,'main/order_summary.html',context)

def update_cart(request,pk,action):
    cart = OrderItems.objects.get(id=pk)
    if action == 'increment':
        cart.qty +=1
        cart.save()
        print(cart.qty)
    else:
        cart.qty -=1
        cart.save()
        print(cart.qty)
    return redirect('order-summary')

def delete_cart_item(request,pk):
    item = OrderItems.objects.get(id=pk)
    item.delete()
    return redirect('order-summary')

def checkout(request):
    orders = request.user.orderitems_set.all()
    final_price = 0
    for i in orders:
        final_price += i.price()
    form= CheckoutForm()
    if request.method == 'POST':
        if form.is_valid():
            form = CheckoutForm(request.POST)
            

    context = {'orders':orders,'finalprice':final_price,'form':form,'couponform': CouponForm(),'DISPLAY_COUPON_FORM': True}
    return render(request,'main/checkout.html',context)

""" def get_coupon(request, code):
    try:
        coupon = Coupon.objects.get(code=code)
        return coupon
    except ObjectDoesNotExist:
        messages.info(request, "This coupon does not exist")
        return redirect("checkout")


def addCoupon(request):
    if request.method == 'POST':
        form = CouponForm(request.POST)
        if form.is_valid():
            try:
                code = form.cleaned_data.get('code')
                order = OrderItems.objects.get(
                    user=request.user, ordered=False)
                order.coupon = get_coupon(request, code)
                order.save()
                messages.success(request, "Successfully added coupon")
                return redirect("checkout")
            except ObjectDoesNotExist:
                messages.info(request, "You do not have an active order")
                return redirect("checkout")



    return redirect('checkout') """

main/templates/main/account_settings.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
{% include 'main/nav.html' %}
{% load crispy_forms_tags %}

<section class="section-cta" id="cta">
	<div class="container">
	  <div class="cta">
		<div class="card card-body frosted-glass">
			<h3 class"heading-tertiary iou" style="align-self:center;padding:40px;">Account Settings</h3>
			{% if request.user.customer.profile_picure %}
			<img src="{{request.user.customer.profile_picure.url}}" class="avatar" alt="avatar">
			{% endif %}
			<br>
			<br>
			<button type="submit" class="btn btn--form sub">Update</button>
		</div>
		<div class="cta-text-box">
		  

		  <form class="cta-form" name="sign-up" netlify method="POST" action="" enctype="multipart/form-data">
			{% csrf_token %}
			{% for i in form %}
			<label for="id_first_name">{{i.label}}:</label>
			<div >{{i}}</div>
			{% endfor %}

			

			<!-- <input type="checkbox" />
			<input type="number" /> -->
		  
		</div>
		
		</form>
		<div>
	</div>
  </section>
  <footer class="py-5 bg-dark">
	<div class="container"><p class="m-0 text-center text-white">Copyright &copy; Night Shoppers 2022</p></div>
</footer>




<style>

	.frosted-glass{
		background: linear-gradient(rgb(255 237 237 / 84%),#ffffff);
	}

	.frosted-glass::before{
		

	}

	.btn--form {
		background-color: #45260a;
		color: #fdf2e9;
		align-self: center;
		padding: 1.2rem;
		padding: 15px 100px;

	  }
	  
	  .btn--form:hover {
		background-color: #fff;
		color: #555;
	  }

	  .sub{
		display: inline-block;
		text-decoration: none;
		font-size: 2rem;
		font-weight: 600;
		padding: 15px 100px;
		border-radius: 9px;
		border: none;
		cursor: pointer;
		font-family: inherit;
		/* transition: background-color 0.3s; */
		transition: all 0.3s;
	  }

	  h3:after{
		display: block;
		height: 2px;
		background-color: #e67e22;
		content: " ";
		width: 90%;
		margin: 0 auto;
		margin-top: 30px;
	  }

	.section-cta {
		/* top / right / bottom / left */
		/* padding: 9.6rem 0 12.8rem 0; */
	  
		/* top / horizontal / left */
		padding: 4.8rem 0 12.8rem;
	  }
	  
	  .cta {
		display: grid;
		/* 2/3 = 66.6% + 1/3 = 33.3% */
		grid-template-columns: 1fr 2fr;
		/* background-color: #e67e22; */
		box-shadow: 0 2.4rem 4.8rem rgba(0, 0, 0, 0.15);
		border-radius: 100px;
	  
		background-image: linear-gradient(to right bottom, #eb984e, #e67e22);
		overflow: hidden;
	  }
	  

	  .avatar{
		align-self: center;
		vertical-align: middle;
		width:300px;
		height:300px;
		border-radius: 50%;
	  }

	  .cta-text-box {
		padding: 4.8rem 6.4rem 6.4rem 6.4rem;
		color: #45260a;
	  }
	  
	  .cta .heading-secondary {
		/* color: #45260a; */
		color: inherit;
		margin-bottom: 3.2rem;
	  }
	  
	  .cta-text {
		font-size: 1.8rem;
		line-height: 1.8;
		margin-bottom: 4.8rem;
	  }

	  .cta-img-box {
		background-image: linear-gradient(
			to right bottom,
			rgba(235, 151, 78, 0.35),
			rgba(230, 125, 34, 0.35)
		  ),
		  url("");
		background-size: contain;
		background-position: center;
	  }
	  
	  .cta-form {
		display: grid;
		grid-template-columns: 1fr 1fr;
		column-gap: 3.2rem;
		row-gap: 2.4rem;
	  }
	  
	  .cta-form label {
		display: block;
		font-size: 1.4rem;
		font-weight: 500;
		margin-bottom: 1.2rem;
	  }
	  
	  .cta-form input,
	  .cta-form select {
		width: 100%;
		padding: 1.2rem;
		font-size: 1.8rem;
		font-family: inherit;
		color: inherit;
		border: none;
		background-color: #fdf2e9;
		border-radius: 9px;
		box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);
	  }
	  
	  .cta-form input::placeholder {
		color: #aaa;
	  }
	  
	  .cta *:focus {
		outline: none;
		box-shadow: 0 0 0 0.8rem rgba(253, 242, 233, 0.5);
	  }

	  @media (max-width: 84em) {
		.hero {
		  max-width: 120rem;
		}
	  
		.heading-primary {
		  font-size: 4.4rem;
		}
	  
		.gallery {
		  grid-template-columns: repeat(2, 1fr);
		}
	  }
	  
	  /**************************/
	  /* BELOW 1200px (Landscape Tablets) */
	  /**************************/
	  
	  @media (max-width: 75em) {
		html {
		  /* 9px / 16px  */
		  font-size: 56.25%;
		}
	  
		.grid {
		  column-gap: 4.8rem;
		  row-gap: 6.4rem;
		}
	  
		.heading-secondary {
		  font-size: 3.6rem;
		}
	  
		.heading-tertiary {
		  font-size: 2.4rem;
		}
	  
		.header {
		  padding: 0 3.2rem;
		}
	  
		.main-nav-list {
		  gap: 3.2rem;
		}
	  
		.hero {
		  gap: 4.8rem;
		}
	  
		.testimonials-container {
		  padding: 9.6rem 3.2rem;
		}
	  }
	  
	  /**************************/
	  /* BELOW 944px (Tablets) */
	  /**************************/
	  
	  @media (max-width: 59em) {
		html {
		  /* 8px / 16px = 0.5 = 50% */
		  font-size: 50%;
		}
	  
		.hero {
		  grid-template-columns: 1fr;
		  padding: 0 8rem;
		  gap: 6.4rem;
		}
	  
		.hero-text-box,
		.hero-img-box {
		  text-align: center;
		}
	  
		.hero-img {
		  width: 60%;
		}
	  
		.delivered-meals {
		  justify-content: center;
		  margin-top: 3.2rem;
		}
	  
		.logos img {
		  height: 2.4rem;
		}
	  
		.step-number {
		  font-size: 7.4rem;
		}
	  
		.meal-content {
		  padding: 2.4rem 3.2rem 3.2rem 3.2rem;
		}
	  
		.section-testimonials {
		  grid-template-columns: 1fr;
		}
	  
		.gallery {
		  grid-template-columns: repeat(6, 1fr);
		}
	  
		.cta {
		  /* 3/5 = 60% + 2/5 = 40% */
		  grid-template-columns: 3fr 2fr;
		}
	  
		.cta-form {
		  grid-template-columns: 1fr;
		}
	  
		.btn--form {
		  margin-top: 1.2rem;
		}
	  
		/* MOBILE NAVIGATION */
		.btn-mobile-nav {
		  display: block;
		  z-index: 9999;
		}
	  
		.main-nav {
		  background-color: rgba(255, 255, 255, 0.9);
		  -webkit-backdrop-filter: blur(5px);
		  backdrop-filter: blur(10px);
		  position: absolute;
		  top: 0;
		  left: 0;
		  width: 100%;
		  height: 100vh;
		  transform: translateX(100%);
	  
		  display: flex;
		  align-items: center;
		  justify-content: center;
		  transition: all 0.5s ease-in;
	  
		  /* Hide navigation */
		  /* Allows NO transitions at all */
		  /* display: none; */
	  
		  /* 1) Hide it visually */
		  opacity: 0;
	  
		  /* 2) Make it unaccessible to mouse and keyboard */
		  pointer-events: none;
	  
		  /* 3) Hide it from screen readers */
		  visibility: hidden;
		}
	  
		.nav-open .main-nav {
		  opacity: 1;
		  pointer-events: auto;
		  visibility: visible;
		  transform: translateX(0);
		}
	  
		.nav-open .icon-mobile-nav[name="close-outline"] {
		  display: block;
		}
	  
		.nav-open .icon-mobile-nav[name="menu-outline"] {
		  display: none;
		}
	  
		.main-nav-list {
		  flex-direction: column;
		  gap: 4.8rem;
		}
	  
		.main-nav-link:link,
		.main-nav-link:visited {
		  font-size: 3rem;
		}
	  }
	  
	  /**************************/
	  /* BELOW 704px (Smaller tablets) */
	  /**************************/
	  
	  @media (max-width: 44em) {
		.grid--3-cols,
		.grid--4-cols {
		  grid-template-columns: repeat(2, 1fr);
		}
	  
		.diets {
		  grid-column: 1 / -1;
		  justify-self: center;
		}
	  
		.heading-secondary {
		  margin-bottom: 4.8rem;
		}
	  
		.pricing-plan {
		  width: 100%;
		}
	  
		.grid--footer {
		  grid-template-columns: repeat(6, 1fr);
		}
	  
		.logo-col,
		.address-col {
		  grid-column: span 3;
		}
	  
		.nav-col {
		  grid-row: 1;
		  grid-column: span 2;
		  margin-bottom: 3.2rem;
		}
	  }
	  
	  /**************************/
	  /* BELOW 544px (Phones) */
	  /**************************/
	  
	  @media (max-width: 34em) {
		.grid {
		  row-gap: 4.8rem;
		}
	  
		.grid--2-cols,
		.grid--3-cols,
		.grid--4-cols {
		  grid-template-columns: 1fr;
		}
	  
		.btn,
		.btn:link,
		.btn:visited {
		  padding: 2.4rem 1.6rem;
		}
	  
		.section-hero {
		  padding: 2.4rem 0 6.4rem 0;
		}
	  
		.hero {
		  padding: 0 3.2rem;
		}
	  
		.hero-img {
		  width: 80%;
		}
	  
		.logos img {
		  height: 1.2rem;
		}
	  
		.step-img-box:nth-child(2) {
		  grid-row: 1;
		}
	  
		.step-img-box:nth-child(6) {
		  grid-row: 5;
		}
	  
		.step-img-box {
		  transform: translateY(2.4rem);
		}
	  
		.testimonials {
		  grid-template-columns: 1fr;
		}
	  
		.gallery {
		  grid-template-columns: repeat(4, 1fr);
		  gap: 1.2rem;
		}
	  
		.cta {
		  grid-template-columns: 1fr;
		}
	  
		.cta-text-box {
		  padding: 3.2rem;
		}
	  
		.cta-img-box {
		  height: 32rem;
		  grid-row: 1;
		}
	  }
	  
	  /* 
	  - Font sizes (px)
	  10 / 12 / 14 / 16 / 18 / 20 / 24 / 30 / 36 / 44 / 52 / 62 / 74 / 86 / 98
	  
	  - Spacing system (px)
	  2 / 4 / 8 / 12 / 16 / 24 / 32 / 48 / 64 / 80 / 96 / 128
	  */
	  
	  /**************************/
	  /* Fixing Safari flexbox gap */
	  /**************************/
	  
	  .no-flexbox-gap .main-nav-list li:not(:last-child) {
		margin-right: 4.8rem;
	  }
	  
	  .no-flexbox-gap .list-item:not(:last-child) {
		margin-bottom: 1.6rem;
	  }
	  
	  .no-flexbox-gap .list-icon:not(:last-child) {
		margin-right: 1.6rem;
	  }
	  
	  .no-flexbox-gap .delivered-faces {
		margin-right: 1.6rem;
	  }
	  
	  .no-flexbox-gap .meal-attribute:not(:last-child) {
		margin-bottom: 2rem;
	  }
	  
	  .no-flexbox-gap .meal-icon {
		margin-right: 1.6rem;
	  }
	  
	  .no-flexbox-gap .footer-row div:not(:last-child) {
		margin-right: 6.4rem;
	  }
	  
	  .no-flexbox-gap .social-links li:not(:last-child) {
		margin-right: 2.4rem;
	  }
	  
	  .no-flexbox-gap .footer-nav li:not(:last-child) {
		margin-bottom: 2.4rem;
	  }
	  
	  @media (max-width: 75em) {
		.no-flexbox-gap .main-nav-list li:not(:last-child) {
		  margin-right: 3.2rem;
		}
	  }
	  
	  @media (max-width: 59em) {
		.no-flexbox-gap .main-nav-list li:not(:last-child) {
		  margin-right: 0;
		  margin-bottom: 4.8rem;
		}
	  }
	  
</style>




{% endblock content %}

main/templates/main/resetcomplete.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}
        <!-- Navigation-->

        <!-- Header-->
        <div class="card" style="margin:50px;">
            <div class="alert alert-success" role="alert">
                <h4 class="alert-heading card-heading">Password reset complete !</h4>
                <p>Your password has been set. You may go ahead and log in now.</p>
                <hr>
                <p class="mb-0"><a href='{% url 'login' %}'>Login<a/></p>
              </div>
            </div>

        {% endblock  %}